CREATE TABLE orders (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
customer_email VARCHAR(255),
total_amount NUMERIC(10,2) NOT NULL,
order_status VARCHAR(50) NOT NULL,
payment_status VARCHAR(50) NOT NULL,
stripe_checkout_session_id VARCHAR(255) UNIQUE,
stripe_payment_intent_id VARCHAR(255),
confirmation_token VARCHAR(255) UNIQUE,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_items (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
order_id BIGINT NOT NULL,
product_id BIGINT NOT NULL,
product_title VARCHAR(255) NOT NULL,
unit_price NUMERIC(10,2) NOT NULL,
quantity INT NOT NULL,
total NUMERIC(10,2) NOT NULL,
CONSTRAINT fk_order_items_order
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
CONSTRAINT fk_order_items_product
    FOREIGN KEY (product_id) REFERENCES products(id)
);